In [1]:
import torch

In [2]:
tensor = torch.tensor([1,2,3])

In [3]:
tensor * tensor

tensor([1, 4, 9])

In [4]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

In [5]:
matrix * matrix

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [6]:
matrix @ matrix

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [7]:
tensor1 = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor2 = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])

In [8]:
tensor1 @ tensor2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [9]:
tensor2 = tensor2.T

In [10]:
tensor1 @ tensor2

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])