# Matris Çarpımı / Matrix Multiplication

🇹🇷 Sinir ağlarının temel işlemi matris çarpımıdır. Bu defterde eleman bazlı çarpım ile matris
çarpımı arasındaki farkı ve çarpımın şekil (shape) kurallarını inceliyoruz.

🇬🇧 Matrix multiplication is the core operation of neural networks. In this notebook we look at the
difference between element-wise and matrix multiplication, and at the shape rules of the latter.

In [1]:
import torch

## Eleman bazlı çarpım / Element-wise multiplication

🇹🇷 `*` operatörü aynı konumdaki elemanları birbiriyle çarpar; sonucun şekli girdiyle aynıdır.

🇬🇧 The `*` operator multiplies the elements at matching positions; the result has the same shape
as the input.

In [2]:
tensor = torch.tensor([1,2,3])

In [3]:
tensor * tensor

tensor([1, 4, 9])

## Matriste iki çarpım türü / Two kinds of multiplication on a matrix

🇹🇷 Aynı matris için `*` eleman bazlı çarpım, `@` ise gerçek matris çarpımı yapar. İkisinin
sonuçları tamamen farklıdır — `@` satır ile sütunun iç çarpımını hesaplar.

🇬🇧 On the same matrix, `*` performs element-wise multiplication while `@` performs true matrix
multiplication. Their results are completely different — `@` computes the dot product of a row
with a column.

In [4]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

In [5]:
matrix * matrix

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [6]:
matrix @ matrix

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

## Şekil kuralı / The shape rule

🇹🇷 Matris çarpımında **iç boyutlar eşleşmelidir**: `(a, b) @ (b, c)` geçerlidir ve sonuç
`(a, c)` şeklindedir. Aşağıdaki `(3,2) @ (3,2)` denemesi bu kurala uymadığı için hata verir.

🇬🇧 In matrix multiplication the **inner dimensions must match**: `(a, b) @ (b, c)` is valid and
yields a result of shape `(a, c)`. The `(3,2) @ (3,2)` attempt below violates this rule and
therefore raises an error.

In [7]:
tensor1 = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor2 = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])

In [8]:
tensor1 @ tensor2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

## Devrik ile şekli düzeltme / Fixing the shape with a transpose

🇹🇷 `.T` matrisin satırlarıyla sütunlarını yer değiştirir. `(3,2)` şeklindeki tensor `(2,3)` olur
ve böylece iç boyutlar eşleşerek çarpım mümkün hale gelir.

🇬🇧 `.T` swaps the rows and columns of a matrix. A tensor of shape `(3,2)` becomes `(2,3)`, so the
inner dimensions match and the multiplication becomes possible.

In [9]:
tensor2 = tensor2.T

In [10]:
tensor1 @ tensor2

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])