# Rastgele Tensorler / Random Tensors

🇹🇷 Sinir ağlarının ağırlıkları rastgele değerlerle başlatılır, bu yüzden rastgele tensor üretmek
temel bir işlemdir. Bu defterde NumPy ve PyTorch'un rastgele üretim fonksiyonlarını karşılaştırıyoruz.

🇬🇧 Neural network weights are initialised with random values, which makes generating random
tensors a fundamental operation. In this notebook we compare the random generators of NumPy and
PyTorch.

In [1]:
import torch
import numpy as np

## NumPy ile rastgele dizi / Random array with NumPy

🇹🇷 `np.random.randn(3,5)` standart normal dağılımdan 3x5'lik bir dizi üretir. Sonuç bir
`numpy.ndarray`'dir; boyutu `ndim`, şekli `shape` ile okunur.

🇬🇧 `np.random.randn(3,5)` produces a 3x5 array drawn from the standard normal distribution. The
result is a `numpy.ndarray`; its dimensionality is read with `ndim` and its shape with `shape`.

In [2]:
random_array = np.random.randn(3,5)

In [3]:
random_array

array([[-1.80916914,  1.67719524,  1.38918929, -1.57002135, -0.26400152],
       [ 0.01983412, -1.66909243, -0.62978632,  2.64069306, -0.77739256],
       [-0.12699277, -0.55077534,  1.54717604, -0.06361862,  1.03017273]])

In [4]:
type(random_array)

numpy.ndarray

In [5]:
random_array.shape

(3, 5)

In [6]:
random_array.ndim

2

## PyTorch ile rastgele tensor / Random tensor with PyTorch

🇹🇷 `torch.rand(size=(3,5))` [0,1) aralığında düzgün (uniform) dağılımlı bir tensor üretir.
NumPy'deki `randn`'den farkı: `randn` normal dağılım, `rand` düzgün dağılım kullanır.

🇬🇧 `torch.rand(size=(3,5))` produces a tensor with a uniform distribution over [0,1). The
difference from NumPy's `randn`: `randn` uses a normal distribution, `rand` a uniform one.

In [7]:
random_matrix = torch.rand(size=(3,5))

In [8]:
random_matrix

tensor([[0.2544, 0.4486, 0.0904, 0.0452, 0.9203],
        [0.6880, 0.8276, 0.6275, 0.4472, 0.7427],
        [0.0705, 0.5378, 0.5691, 0.6892, 0.4337]])

In [9]:
random_matrix.ndim

2

In [10]:
random_matrix.shape

torch.Size([3, 5])

In [11]:
random_matrix.dtype

torch.float32

## Görüntü şeklinde rastgele tensor / Random image-shaped tensor

🇹🇷 `(224, 224, 3)` şekli tipik bir görüntüyü temsil eder: 224 piksel yükseklik, 224 piksel
genişlik ve 3 renk kanalı (RGB). Görüntü modelleri verilerini bu şekilde tensor olarak alır.

🇬🇧 The shape `(224, 224, 3)` represents a typical image: 224 pixels high, 224 pixels wide and 3
colour channels (RGB). Vision models take their input as tensors in exactly this form.

In [12]:
random_image_tensor = torch.rand(size=(224,224,3))

In [13]:
random_image_tensor

tensor([[[0.8068, 0.9659, 0.5072],
         [0.1717, 0.0556, 0.7259],
         [0.0294, 0.2531, 0.4145],
         ...,
         [0.3978, 0.5783, 0.4278],
         [0.9333, 0.2761, 0.6458],
         [0.8692, 0.0456, 0.5277]],

        [[0.7985, 0.7798, 0.8465],
         [0.3756, 0.9999, 0.4477],
         [0.2655, 0.3542, 0.0302],
         ...,
         [0.7668, 0.0863, 0.4577],
         [0.6565, 0.8439, 0.9332],
         [0.8888, 0.5599, 0.2798]],

        [[0.3394, 0.4016, 0.1439],
         [0.0084, 0.2386, 0.5175],
         [0.1091, 0.6492, 0.2440],
         ...,
         [0.9167, 0.8372, 0.6560],
         [0.7579, 0.4208, 0.5949],
         [0.6824, 0.0178, 0.4112]],

        ...,

        [[0.4731, 0.8510, 0.3376],
         [0.5522, 0.2522, 0.7948],
         [0.5227, 0.9179, 0.9302],
         ...,
         [0.9371, 0.2291, 0.4989],
         [0.3454, 0.5969, 0.0409],
         [0.6479, 0.5311, 0.1811]],

        [[0.0233, 0.6416, 0.0171],
         [0.6959, 0.0991, 0.7919],
         [0.

In [14]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [15]:
random_image_tensor.ndim

3