In [1]:
import torch
import numpy as np

In [2]:
zeros = torch.zeros(size = (3,2))

In [3]:
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
ones = torch.ones(size = (3,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [7]:
vector_with_arange = torch.arange(start=0,end=10,step=2)

In [8]:
vector_with_arange

tensor([0, 2, 4, 6, 8])

In [9]:
similar_ones = torch.ones_like(input=vector_with_arange)

In [10]:
similar_ones

tensor([1, 1, 1, 1, 1])

In [11]:
x_tensor = torch.tensor([1,2,3])

In [12]:
x_tensor + 15

tensor([16, 17, 18])

In [13]:
x_tensor * 3

tensor([3, 6, 9])

In [14]:
x_tensor * 3.14

tensor([3.1400, 6.2800, 9.4200])

In [15]:
x_tensor.multiply(10)

tensor([10, 20, 30])

In [16]:
x_tensor.add(20)

tensor([21, 22, 23])

In [17]:
x_tensor.divide(2)

tensor([0.5000, 1.0000, 1.5000])

In [18]:
x_tensor * x_tensor

tensor([1, 4, 9])

In [19]:
x_tensor + x_tensor

tensor([2, 4, 6])

In [20]:
x_tensor + x_tensor

tensor([2, 4, 6])

In [21]:
x_tensor / x_tensor

tensor([1., 1., 1.])

In [22]:
y_tensor = torch.tensor([4,5])