# Tensor Üretimi ve Matematik İşlemleri / Tensor Creation and Math Operations

🇹🇷 Bu defterde hazır tensor üretme fonksiyonlarını (`zeros`, `ones`, `arange`, `ones_like`) ve
eleman bazlı (element-wise) matematik işlemlerini inceliyoruz.

🇬🇧 In this notebook we look at the ready-made tensor creation functions (`zeros`, `ones`,
`arange`, `ones_like`) and at element-wise math operations.

In [1]:
import torch
import numpy as np

## Sıfırlar ve birler / Zeros and ones

🇹🇷 `torch.zeros` ve `torch.ones` verilen şekilde tamamı 0 veya 1 olan tensorler üretir. Bir
tensoru başlangıç değeriyle doldurmak ya da maske oluşturmak için kullanılır.

🇬🇧 `torch.zeros` and `torch.ones` create tensors of the given shape filled entirely with 0 or 1.
They are used to initialise a tensor with a starting value or to build masks.

In [2]:
zeros = torch.zeros(size = (3,2))

In [3]:
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [4]:
ones = torch.ones(size = (3,2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

## Aralık üretme / Creating a range

🇹🇷 `torch.arange(start, end, step)` belirtilen adımla artan bir vektör üretir. `end` değeri
aralığa dahil değildir.

🇬🇧 `torch.arange(start, end, step)` produces a vector increasing by the given step. The `end`
value is exclusive.

In [7]:
vector_with_arange = torch.arange(start=0,end=10,step=2)

In [8]:
vector_with_arange

tensor([0, 2, 4, 6, 8])

## Başka bir tensorün şeklini kopyalama / Copying another tensor's shape

🇹🇷 `torch.ones_like(input=...)` verilen tensorle aynı şekle sahip, tamamı 1 olan yeni bir tensor
üretir. Şekli elle yazmadan aynı boyutta tensor oluşturmanın kısa yoludur.

🇬🇧 `torch.ones_like(input=...)` creates a new tensor of ones with the same shape as the given
tensor. It is a shortcut for matching a shape without writing it out by hand.

In [9]:
similar_ones = torch.ones_like(input=vector_with_arange)

In [10]:
similar_ones

tensor([1, 1, 1, 1, 1])

## Skaler ile işlemler (yayınlama) / Operations with a scalar (broadcasting)

🇹🇷 Bir tensor ile tek bir sayı işleme sokulduğunda, sayı tüm elemanlara ayrı ayrı uygulanır.
Buna yayınlama (broadcasting) denir. Ondalıklı bir sayıyla çarpmak sonucun tipini float yapar.

🇬🇧 When a tensor is combined with a single number, the number is applied to every element
separately. This is called broadcasting. Multiplying by a decimal number turns the result into a
float tensor.

In [11]:
x_tensor = torch.tensor([1,2,3])

In [12]:
x_tensor + 15

tensor([16, 17, 18])

In [13]:
x_tensor * 3

tensor([3, 6, 9])

In [14]:
x_tensor * 3.14

tensor([3.1400, 6.2800, 9.4200])

## Operatörler ve metot karşılıkları / Operators and their method forms

🇹🇷 `*`, `+`, `/` operatörlerinin metot karşılıkları vardır: `multiply()`, `add()`, `divide()`.
İkisi de aynı işi yapar; metot biçimi zincirleme çağrılarda daha okunaklı olabilir.

🇬🇧 The `*`, `+` and `/` operators have method equivalents: `multiply()`, `add()`, `divide()`.
Both do the same job; the method form can read better in chained calls.

In [15]:
x_tensor.multiply(10)

tensor([10, 20, 30])

In [16]:
x_tensor.add(20)

tensor([21, 22, 23])

In [17]:
x_tensor.divide(2)

tensor([0.5000, 1.0000, 1.5000])

## İki tensor arasında eleman bazlı işlemler / Element-wise operations between two tensors

🇹🇷 Aynı şekle sahip iki tensor arasındaki işlemler eleman eleman yapılır: birinci elemanla
birinci, ikinciyle ikinci... Bu, matris çarpımından farklıdır.

🇬🇧 Operations between two tensors of the same shape are applied element by element: first with
first, second with second, and so on. This is different from matrix multiplication.

In [18]:
x_tensor * x_tensor

tensor([1, 4, 9])

In [19]:
x_tensor + x_tensor

tensor([2, 4, 6])

In [20]:
x_tensor + x_tensor

tensor([2, 4, 6])

In [21]:
x_tensor / x_tensor

tensor([1., 1., 1.])

## Şekil uyumu / Shape compatibility

🇹🇷 Eleman bazlı işlemlerin çalışabilmesi için şekillerin uyumlu olması gerekir. Farklı uzunlukta
iki vektör (ör. 3 ve 2 elemanlı) doğrudan işleme sokulamaz.

🇬🇧 Element-wise operations require compatible shapes. Two vectors of different lengths (e.g. one
with 3 and one with 2 elements) cannot be combined directly.

In [22]:
y_tensor = torch.tensor([4,5])